// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5vA4t-4MerlZfB6bhpfRS3AUhwtf7n7U',
    appId: '1:835948077761:android:8347ae7e356dc140e6aa40',
    messagingSenderId: '835948077761',
    projectId: 'demo1-17dbe',
    storageBucket: 'demo1-17dbe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvn9YsaPaMNQQUswEYQeGz-PHcCkgDhGM',
    appId: '1:835948077761:web:c88cf56f48adb199e6aa40',
    messagingSenderId: '835948077761',
    projectId: 'demo1-17dbe',
    authDomain: 'demo1-17dbe.firebaseapp.com',
    storageBucket: 'demo1-17dbe.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvn9YsaPaMNQQUswEYQeGz-PHcCkgDhGM',
    appId: '1:835948077761:web:83592e93996c6377e6aa40',
    messagingSenderId: '835948077761',
    projectId: 'demo1-17dbe',
    authDomain: 'demo1-17dbe.firebaseapp.com',
    storageBucket: 'demo1-17dbe.firebasestorage.app',
  );
}
