"""Shared Enums for all models"""
from enum import Enum


class UserRole(str, Enum):
    USER = "USER"
    ADMIN = "ADMIN"
    STAFF = "STAFF"
    STORE = "STORE"


class RequestStatus(str, Enum):
    RAISED = "RAISED"
    REPLIED = "REPLIED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    REASSIGN_REQUESTED = "REASSIGN_REQUESTED"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"


class TrackEventType(str, Enum):
    RAISED = "RAISED"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    REASSIGN_REQUESTED = "REASSIGN_REQUESTED"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    STORE_REQUEST_CREATED = "STORE_REQUEST_CREATED"
    STORE_REQUEST_APPROVED = "STORE_REQUEST_APPROVED"
    STORE_REQUEST_REJECTED = "STORE_REQUEST_REJECTED"
    STORE_REQUEST_FULFILLED = "STORE_REQUEST_FULFILLED"
    REPLIED = "REPLIED"


class StoreRequestStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FULFILLED = "FULFILLED"


class DevicePlatform(str, Enum):
    ANDROID = "android"
    IOS = "ios"
    UNKNOWN = "unknown"
